# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false


# A minimal left prompt
# format = "$character"

# move the rest of the prompt to the right
# right_format = "$all"

[character]
success_symbol = '[Ïž](bold bright-blue)'

[direnv]
disabled = true

[sudo]
disabled = false

[memory_usage]
disabled = true

[package]
disabled = true
