# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false


# A minimal left prompt
# format = "$character"

# move the rest of the prompt to the right
# right_format = "$all"

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
# U+1D713
success_symbol = '[ğœ“](bold bright-blue)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

[direnv]
disabled = true

[sudo]
disabled = false

[memory_usage]
disabled = true

[package]
disabled = true
